---
- name: Install wordpress on CentOS 7
  # gather_facts: no
  hosts: 3.19.32.24
  become: true
  become_method: sudo
  user: centos
  vars:
    mysql_root_password: "password"
  tasks:
    - name: add users
      user:
        name: "{{ item }}"
        state: present
      with_items:
        - bob
        - ben
        - lisa
        - katty
    - name: Install remi repo.
      yum:
        name: http://rpms.famillecollet.com/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm
        state: present
    # - name: install remi repo 7
    #   shell: "yum install http://rpms.remirepo.net/enterprise/remi-release-7.rpm -y"   (this will get you the repo, but if its already installed will give an error)
    - name: enable remi-php72
      shell: "yum-config-manager --enable remi-php72"
    - name: Install httpd
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - httpd
        - php
        - mariadb-server
        - mysql
        - elinks
        - php-mysql
        - php-gd
      ignore_errors: yes
    - name: enable MariaDB
      service: name=mariadb enabled=yes
    - name: update mysql root password for all root accounts
      mysql_user:
        name: root
        host: "{{ item }}"
        password: "{{ mysql_root_password }}"
        login_user: root
        login_password: "{{ mysql_root_password }}"
        check_implicit_admin: yes
        priv: "*.*:ALL,GRANT"
    - name: create a new database wordpressdb
      mysql_db: name=wordpressdb state=present login_user=root login_password={{ mysql_root_password }}
      with_items:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost
    # - name: Download wordpress
    #   get_url:
    #     url: https://wordpress.org/latest.tar.gz
    #     dest: /tmp/
    - name: Unzip wordpress
      unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: /var/www/html/
        remote_src: yes
    - name: move files
      shell: "mv /var/www/html/wordpress/*  /var/www/html/"
      ignore_errors: yes
    - name: Move index.html
      shell: "mv /var/www/html/index.html /tmp/"
      ignore_errors: true
    - command: chown -R apache:apache /var/www/html/
    - name: run apache
      systemd:
        name: httpd
        state: restarted
        enabled: yes
      ignore_errors: yes
- name: add a record to route53
  hosts: localhost
  gather_facts: false
  tasks:
    - route53:
        command: create
        zone: maxirs.com
        record: test.maxirs.com
        type: A
        ttl: 60
        value: 3.19.32.24
        wait: yes