---
- name: create / remove users and public keys
  # gather_facts: no
  hosts: localhost
  become: true
  become_method: sudo
  user: centos
  vars_prompt:
    - name: username
      prompt: "What is your username?"
      private: no
      
  tasks:
    - debug:
        msg: 'Logging in as {{ username }}'
    - tags: add user
      name: add users
      user:
        name: "{{username}}"
        state: present
        generate_ssh_key: true

    - name: Set authorized key took from file
      authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ lookup('file', '/home/ec2-user/.ssh/id_rsa.pub') }}"
    - tags: remove user
      name: removing users
      user:
        name: "{{username}}"
        state: absent
        remove: yes